/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc4javatoolbox.ifc4;
/**
 * This is a default implementation of the entity IfcAppliedValue<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcAppliedValue extends InternalAccessClass implements IfcObjectReferenceSelect, IfcMetricValueSelect, IfcResourceObjectSelect, ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcLabel","IfcText","IfcAppliedValueSelect","IfcMeasureWithUnit","IfcDate","IfcDate","IfcLabel","IfcLabel","IfcArithmeticOperatorEnum","LIST<IfcAppliedValue>"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** Name is an OPTIONAL attribute**/
	protected IfcLabel Name;
	/** Description is an OPTIONAL attribute**/
	protected IfcText Description;
	/** AppliedValue is an OPTIONAL attribute**/
	protected IfcAppliedValueSelect AppliedValue;
	/** UnitBasis is an OPTIONAL attribute**/
	protected IfcMeasureWithUnit UnitBasis;
	/** ApplicableDate is an OPTIONAL attribute**/
	protected IfcDate ApplicableDate;
	/** FixedUntilDate is an OPTIONAL attribute**/
	protected IfcDate FixedUntilDate;
	/** Category is an OPTIONAL attribute**/
	protected IfcLabel Category;
	/** Condition is an OPTIONAL attribute**/
	protected IfcLabel Condition;
	/** ArithmeticOperator is an OPTIONAL attribute**/
	protected IfcArithmeticOperatorEnum ArithmeticOperator;
	/** Components is an OPTIONAL attribute**/
	protected LIST<IfcAppliedValue> Components;
	protected SET<IfcExternalReferenceRelationship> HasExternalReference_Inverse;
	/**
	* The default constructor.
	**/
	public IfcAppliedValue(){}

	/**
	* Constructs a new IfcAppliedValue object using the given parameters.
	*
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param AppliedValue OPTIONAL parameter of type IfcAppliedValueSelect
	* @param UnitBasis OPTIONAL parameter of type IfcMeasureWithUnit
	* @param ApplicableDate OPTIONAL parameter of type IfcDate
	* @param FixedUntilDate OPTIONAL parameter of type IfcDate
	* @param Category OPTIONAL parameter of type IfcLabel
	* @param Condition OPTIONAL parameter of type IfcLabel
	* @param ArithmeticOperator OPTIONAL parameter of type IfcArithmeticOperatorEnum
	* @param Components OPTIONAL parameter of type LIST<IfcAppliedValue>
	**/
	public IfcAppliedValue(IfcLabel Name, IfcText Description, IfcAppliedValueSelect AppliedValue, IfcMeasureWithUnit UnitBasis, IfcDate ApplicableDate, IfcDate FixedUntilDate, IfcLabel Category, IfcLabel Condition, IfcArithmeticOperatorEnum ArithmeticOperator, LIST<IfcAppliedValue> Components)
	{
		this.Name = Name;
		this.Description = Description;
		this.AppliedValue = AppliedValue;
		this.UnitBasis = UnitBasis;
		this.ApplicableDate = ApplicableDate;
		this.FixedUntilDate = FixedUntilDate;
		this.Category = Category;
		this.Condition = Condition;
		this.ArithmeticOperator = ArithmeticOperator;
		this.Components = Components;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcAppliedValue object using the given parameters.
	*
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param AppliedValue OPTIONAL parameter of type IfcAppliedValueSelect
	* @param UnitBasis OPTIONAL parameter of type IfcMeasureWithUnit
	* @param ApplicableDate OPTIONAL parameter of type IfcDate
	* @param FixedUntilDate OPTIONAL parameter of type IfcDate
	* @param Category OPTIONAL parameter of type IfcLabel
	* @param Condition OPTIONAL parameter of type IfcLabel
	* @param ArithmeticOperator OPTIONAL parameter of type IfcArithmeticOperatorEnum
	* @param Components OPTIONAL parameter of type LIST<IfcAppliedValue>
	**/
	public void setParameters(IfcLabel Name, IfcText Description, IfcAppliedValueSelect AppliedValue, IfcMeasureWithUnit UnitBasis, IfcDate ApplicableDate, IfcDate FixedUntilDate, IfcLabel Category, IfcLabel Condition, IfcArithmeticOperatorEnum ArithmeticOperator, LIST<IfcAppliedValue> Components)
	{
		this.Name = Name;
		this.Description = Description;
		this.AppliedValue = AppliedValue;
		this.UnitBasis = UnitBasis;
		this.ApplicableDate = ApplicableDate;
		this.FixedUntilDate = FixedUntilDate;
		this.Category = Category;
		this.Condition = Condition;
		this.ArithmeticOperator = ArithmeticOperator;
		this.Components = Components;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	@SuppressWarnings("unchecked")
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.Name = (IfcLabel) parameters.get(0);
		this.Description = (IfcText) parameters.get(1);
		this.AppliedValue = (IfcAppliedValueSelect) parameters.get(2);
		this.UnitBasis = (IfcMeasureWithUnit) parameters.get(3);
		this.ApplicableDate = (IfcDate) parameters.get(4);
		this.FixedUntilDate = (IfcDate) parameters.get(5);
		this.Category = (IfcLabel) parameters.get(6);
		this.Condition = (IfcLabel) parameters.get(7);
		this.ArithmeticOperator = (IfcArithmeticOperatorEnum) parameters.get(8);
		this.Components = (LIST<IfcAppliedValue>) parameters.get(9);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		listenerList = null;
		HasExternalReference_Inverse = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcAppliedValue.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCAPPLIEDVALUE(");
		if(getRedefinedDerivedAttributeTypes().contains("Name")) stepString = stepString.concat("*,");
		else{
		if(this.Name != null)		stepString = stepString.concat(((RootInterface)this.Name).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Description")) stepString = stepString.concat("*,");
		else{
		if(this.Description != null)		stepString = stepString.concat(((RootInterface)this.Description).getStepParameter(IfcText.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("AppliedValue")) stepString = stepString.concat("*,");
		else{
		if(this.AppliedValue != null)		stepString = stepString.concat(((RootInterface)this.AppliedValue).getStepParameter(IfcAppliedValueSelect.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("UnitBasis")) stepString = stepString.concat("*,");
		else{
		if(this.UnitBasis != null)		stepString = stepString.concat(((RootInterface)this.UnitBasis).getStepParameter(IfcMeasureWithUnit.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ApplicableDate")) stepString = stepString.concat("*,");
		else{
		if(this.ApplicableDate != null)		stepString = stepString.concat(((RootInterface)this.ApplicableDate).getStepParameter(IfcDate.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("FixedUntilDate")) stepString = stepString.concat("*,");
		else{
		if(this.FixedUntilDate != null)		stepString = stepString.concat(((RootInterface)this.FixedUntilDate).getStepParameter(IfcDate.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Category")) stepString = stepString.concat("*,");
		else{
		if(this.Category != null)		stepString = stepString.concat(((RootInterface)this.Category).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Condition")) stepString = stepString.concat("*,");
		else{
		if(this.Condition != null)		stepString = stepString.concat(((RootInterface)this.Condition).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ArithmeticOperator")) stepString = stepString.concat("*,");
		else{
		if(this.ArithmeticOperator != null)		stepString = stepString.concat(((RootInterface)this.ArithmeticOperator).getStepParameter(IfcArithmeticOperatorEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Components")) stepString = stepString.concat("*);");
		else{
		if(this.Components != null)		stepString = stepString.concat(((RootInterface)this.Components).getStepParameter(IfcAppliedValue.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method returns a copy of the set of the HasExternalReference_Inverse attribute.
	*
	* @return a copy of the HasExternalReference_Inverse set
	**/
	public SET<IfcExternalReferenceRelationship> getHasExternalReference_Inverse()
	{
		if(this.HasExternalReference_Inverse != null)
			return new SET<IfcExternalReferenceRelationship>(this.HasExternalReference_Inverse);
		return null;
	}

	/**
	* This method sets the Name attribute to the given value.
	*
	* @param Name DEMANDED value to set - may not be null
	**/
	public void setName(IfcLabel Name)
	{
		this.Name = Name;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Name attribute.
	*
	* @return the value of Name
	/**/
	public IfcLabel getName()
	{
		return this.Name;
	}

	/**
	* This method sets the Description attribute to the given value.
	*
	* @param Description DEMANDED value to set - may not be null
	**/
	public void setDescription(IfcText Description)
	{
		this.Description = Description;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Description attribute.
	*
	* @return the value of Description
	/**/
	public IfcText getDescription()
	{
		return this.Description;
	}

	/**
	* This method sets the AppliedValue attribute to the given value.
	*
	* @param AppliedValue DEMANDED value to set - may not be null
	**/
	public void setAppliedValue(IfcAppliedValueSelect AppliedValue)
	{
		this.AppliedValue = AppliedValue;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the AppliedValue attribute.
	*
	* @return the value of AppliedValue
	/**/
	public IfcAppliedValueSelect getAppliedValue()
	{
		return this.AppliedValue;
	}

	/**
	* This method sets the UnitBasis attribute to the given value.
	*
	* @param UnitBasis DEMANDED value to set - may not be null
	**/
	public void setUnitBasis(IfcMeasureWithUnit UnitBasis)
	{
		this.UnitBasis = UnitBasis;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the UnitBasis attribute.
	*
	* @return the value of UnitBasis
	/**/
	public IfcMeasureWithUnit getUnitBasis()
	{
		return this.UnitBasis;
	}

	/**
	* This method sets the ApplicableDate attribute to the given value.
	*
	* @param ApplicableDate DEMANDED value to set - may not be null
	**/
	public void setApplicableDate(IfcDate ApplicableDate)
	{
		this.ApplicableDate = ApplicableDate;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the ApplicableDate attribute.
	*
	* @return the value of ApplicableDate
	/**/
	public IfcDate getApplicableDate()
	{
		return this.ApplicableDate;
	}

	/**
	* This method sets the FixedUntilDate attribute to the given value.
	*
	* @param FixedUntilDate DEMANDED value to set - may not be null
	**/
	public void setFixedUntilDate(IfcDate FixedUntilDate)
	{
		this.FixedUntilDate = FixedUntilDate;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the FixedUntilDate attribute.
	*
	* @return the value of FixedUntilDate
	/**/
	public IfcDate getFixedUntilDate()
	{
		return this.FixedUntilDate;
	}

	/**
	* This method sets the Category attribute to the given value.
	*
	* @param Category DEMANDED value to set - may not be null
	**/
	public void setCategory(IfcLabel Category)
	{
		this.Category = Category;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Category attribute.
	*
	* @return the value of Category
	/**/
	public IfcLabel getCategory()
	{
		return this.Category;
	}

	/**
	* This method sets the Condition attribute to the given value.
	*
	* @param Condition DEMANDED value to set - may not be null
	**/
	public void setCondition(IfcLabel Condition)
	{
		this.Condition = Condition;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Condition attribute.
	*
	* @return the value of Condition
	/**/
	public IfcLabel getCondition()
	{
		return this.Condition;
	}

	/**
	* This method sets the ArithmeticOperator attribute to the given value.
	*
	* @param ArithmeticOperator DEMANDED value to set - may not be null
	**/
	public void setArithmeticOperator(IfcArithmeticOperatorEnum ArithmeticOperator)
	{
		this.ArithmeticOperator = ArithmeticOperator;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the ArithmeticOperator attribute.
	*
	* @return the value of ArithmeticOperator
	/**/
	public IfcArithmeticOperatorEnum getArithmeticOperator()
	{
		return this.ArithmeticOperator;
	}

	/**
	* This method sets the Components attribute to the given value.
	*
	* @param Components DEMANDED value to set - may not be null
	**/
	public void setComponents(LIST<IfcAppliedValue> Components)
	{
		this.Components = Components;
		fireChangeEvent();
	}

	/**
	* This method returns a copy of the list of the Components attribute.
	*
	* @return a copy of the Components list
	**/
	public LIST<IfcAppliedValue> getComponents()
	{
		if(this.Components != null)
			return new LIST<IfcAppliedValue>(this.Components);
		return null;
	}

	/**
	* This method adds an IfcAppliedValue object to the Components list.
	* @param Components element to be appended to this list.
	**/
	public void addComponents(IfcAppliedValue Components)
	{
		if(this.Components == null)
			this.Components = new LIST<IfcAppliedValue>();
		this.Components.add(Components);
		fireChangeEvent();
	}

	/**
	* This method adds a collection of IfcAppliedValue objects to the Components list.
	* @param Components collection containing elements to be added to this list.
	**/
	public void addAllComponents(java.util.Collection<IfcAppliedValue> Components)
	{
		if(this.Components == null)
			this.Components = new LIST<IfcAppliedValue>();
		this.Components.addAll(Components);
		fireChangeEvent();
	}

	/**
	* This method removes all elements from the Components list.
	**/
	public void clearComponents()
	{
		if(this.Components != null)
		{
			this.Components.clear();
			fireChangeEvent();
		}
	}

	/**
	* This method removes an IfcAppliedValue object from the Components list.
	* @param Components element to be removed from this list.
	**/
	public void removeComponents(IfcAppliedValue Components)
	{
		if(this.Components != null)
		{
			this.Components.remove(Components);
			fireChangeEvent();
		}
	}

	/**
	* This method removes a collection of IfcAppliedValue objects from the Components list.
	* @param Components collection containing elements to be removed from this list.
	**/
	public void removeAllComponents(java.util.Collection<IfcAppliedValue> Components)
	{
		if(this.Components != null)
		{
			this.Components.removeAll(Components);
			fireChangeEvent();
		}
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	@SuppressWarnings("unchecked")
	public Object clone()
	{
		IfcAppliedValue ifcAppliedValue = new IfcAppliedValue();
		if(this.Name != null)
			ifcAppliedValue.setName((IfcLabel)this.Name.clone());
		if(this.Description != null)
			ifcAppliedValue.setDescription((IfcText)this.Description.clone());
		if(this.AppliedValue != null)
			ifcAppliedValue.setAppliedValue((IfcAppliedValueSelect)this.AppliedValue.clone());
		if(this.UnitBasis != null)
			ifcAppliedValue.setUnitBasis((IfcMeasureWithUnit)this.UnitBasis.clone());
		if(this.ApplicableDate != null)
			ifcAppliedValue.setApplicableDate((IfcDate)this.ApplicableDate.clone());
		if(this.FixedUntilDate != null)
			ifcAppliedValue.setFixedUntilDate((IfcDate)this.FixedUntilDate.clone());
		if(this.Category != null)
			ifcAppliedValue.setCategory((IfcLabel)this.Category.clone());
		if(this.Condition != null)
			ifcAppliedValue.setCondition((IfcLabel)this.Condition.clone());
		if(this.ArithmeticOperator != null)
			ifcAppliedValue.setArithmeticOperator((IfcArithmeticOperatorEnum)this.ArithmeticOperator.clone());
		if(this.Components != null)
			ifcAppliedValue.setComponents((LIST<IfcAppliedValue>)this.Components.clone());
		return ifcAppliedValue;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcAppliedValue ifcAppliedValue = new IfcAppliedValue();
		if(this.Name != null)
			ifcAppliedValue.setName(this.Name);
		if(this.Description != null)
			ifcAppliedValue.setDescription(this.Description);
		if(this.AppliedValue != null)
			ifcAppliedValue.setAppliedValue(this.AppliedValue);
		if(this.UnitBasis != null)
			ifcAppliedValue.setUnitBasis(this.UnitBasis);
		if(this.ApplicableDate != null)
			ifcAppliedValue.setApplicableDate(this.ApplicableDate);
		if(this.FixedUntilDate != null)
			ifcAppliedValue.setFixedUntilDate(this.FixedUntilDate);
		if(this.Category != null)
			ifcAppliedValue.setCategory(this.Category);
		if(this.Condition != null)
			ifcAppliedValue.setCondition(this.Condition);
		if(this.ArithmeticOperator != null)
			ifcAppliedValue.setArithmeticOperator(this.ArithmeticOperator);
		if(this.Components != null)
			ifcAppliedValue.setComponents(this.Components);
		return ifcAppliedValue;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
