/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc4javatoolbox.ifc4;
/**
 * This is a default implementation of the entity IfcApproval<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcApproval extends InternalAccessClass implements IfcResourceObjectSelect, ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcIdentifier","IfcLabel","IfcText","IfcDateTime","IfcLabel","IfcLabel","IfcText","IfcActorSelect","IfcActorSelect"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** Identifier is an OPTIONAL attribute**/
	protected IfcIdentifier Identifier;
	/** Name is an OPTIONAL attribute**/
	protected IfcLabel Name;
	/** Description is an OPTIONAL attribute**/
	protected IfcText Description;
	/** TimeOfApproval is an OPTIONAL attribute**/
	protected IfcDateTime TimeOfApproval;
	/** Status is an OPTIONAL attribute**/
	protected IfcLabel Status;
	/** Level is an OPTIONAL attribute**/
	protected IfcLabel Level;
	/** Qualifier is an OPTIONAL attribute**/
	protected IfcText Qualifier;
	/** RequestingApproval is an OPTIONAL attribute**/
	protected IfcActorSelect RequestingApproval;
	/** GivingApproval is an OPTIONAL attribute**/
	protected IfcActorSelect GivingApproval;
	protected SET<IfcExternalReferenceRelationship> HasExternalReferences_Inverse;
	protected SET<IfcRelAssociatesApproval> ApprovedObjects_Inverse;
	protected SET<IfcResourceApprovalRelationship> ApprovedResources_Inverse;
	protected SET<IfcApprovalRelationship> IsRelatedWith_Inverse;
	protected SET<IfcApprovalRelationship> Relates_Inverse;
	/**
	* The default constructor.
	**/
	public IfcApproval(){}

	/**
	* Constructs a new IfcApproval object using the given parameters.
	*
	* @param Identifier OPTIONAL parameter of type IfcIdentifier
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param TimeOfApproval OPTIONAL parameter of type IfcDateTime
	* @param Status OPTIONAL parameter of type IfcLabel
	* @param Level OPTIONAL parameter of type IfcLabel
	* @param Qualifier OPTIONAL parameter of type IfcText
	* @param RequestingApproval OPTIONAL parameter of type IfcActorSelect
	* @param GivingApproval OPTIONAL parameter of type IfcActorSelect
	**/
	public IfcApproval(IfcIdentifier Identifier, IfcLabel Name, IfcText Description, IfcDateTime TimeOfApproval, IfcLabel Status, IfcLabel Level, IfcText Qualifier, IfcActorSelect RequestingApproval, IfcActorSelect GivingApproval)
	{
		this.Identifier = Identifier;
		this.Name = Name;
		this.Description = Description;
		this.TimeOfApproval = TimeOfApproval;
		this.Status = Status;
		this.Level = Level;
		this.Qualifier = Qualifier;
		this.RequestingApproval = RequestingApproval;
		this.GivingApproval = GivingApproval;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcApproval object using the given parameters.
	*
	* @param Identifier OPTIONAL parameter of type IfcIdentifier
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param TimeOfApproval OPTIONAL parameter of type IfcDateTime
	* @param Status OPTIONAL parameter of type IfcLabel
	* @param Level OPTIONAL parameter of type IfcLabel
	* @param Qualifier OPTIONAL parameter of type IfcText
	* @param RequestingApproval OPTIONAL parameter of type IfcActorSelect
	* @param GivingApproval OPTIONAL parameter of type IfcActorSelect
	**/
	public void setParameters(IfcIdentifier Identifier, IfcLabel Name, IfcText Description, IfcDateTime TimeOfApproval, IfcLabel Status, IfcLabel Level, IfcText Qualifier, IfcActorSelect RequestingApproval, IfcActorSelect GivingApproval)
	{
		this.Identifier = Identifier;
		this.Name = Name;
		this.Description = Description;
		this.TimeOfApproval = TimeOfApproval;
		this.Status = Status;
		this.Level = Level;
		this.Qualifier = Qualifier;
		this.RequestingApproval = RequestingApproval;
		this.GivingApproval = GivingApproval;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.Identifier = (IfcIdentifier) parameters.get(0);
		this.Name = (IfcLabel) parameters.get(1);
		this.Description = (IfcText) parameters.get(2);
		this.TimeOfApproval = (IfcDateTime) parameters.get(3);
		this.Status = (IfcLabel) parameters.get(4);
		this.Level = (IfcLabel) parameters.get(5);
		this.Qualifier = (IfcText) parameters.get(6);
		this.RequestingApproval = (IfcActorSelect) parameters.get(7);
		this.GivingApproval = (IfcActorSelect) parameters.get(8);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		listenerList = null;
		HasExternalReferences_Inverse = null;
		ApprovedObjects_Inverse = null;
		ApprovedResources_Inverse = null;
		IsRelatedWith_Inverse = null;
		Relates_Inverse = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcApproval.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCAPPROVAL(");
		if(getRedefinedDerivedAttributeTypes().contains("Identifier")) stepString = stepString.concat("*,");
		else{
		if(this.Identifier != null)		stepString = stepString.concat(((RootInterface)this.Identifier).getStepParameter(IfcIdentifier.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Name")) stepString = stepString.concat("*,");
		else{
		if(this.Name != null)		stepString = stepString.concat(((RootInterface)this.Name).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Description")) stepString = stepString.concat("*,");
		else{
		if(this.Description != null)		stepString = stepString.concat(((RootInterface)this.Description).getStepParameter(IfcText.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("TimeOfApproval")) stepString = stepString.concat("*,");
		else{
		if(this.TimeOfApproval != null)		stepString = stepString.concat(((RootInterface)this.TimeOfApproval).getStepParameter(IfcDateTime.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Status")) stepString = stepString.concat("*,");
		else{
		if(this.Status != null)		stepString = stepString.concat(((RootInterface)this.Status).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Level")) stepString = stepString.concat("*,");
		else{
		if(this.Level != null)		stepString = stepString.concat(((RootInterface)this.Level).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Qualifier")) stepString = stepString.concat("*,");
		else{
		if(this.Qualifier != null)		stepString = stepString.concat(((RootInterface)this.Qualifier).getStepParameter(IfcText.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("RequestingApproval")) stepString = stepString.concat("*,");
		else{
		if(this.RequestingApproval != null)		stepString = stepString.concat(((RootInterface)this.RequestingApproval).getStepParameter(IfcActorSelect.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("GivingApproval")) stepString = stepString.concat("*);");
		else{
		if(this.GivingApproval != null)		stepString = stepString.concat(((RootInterface)this.GivingApproval).getStepParameter(IfcActorSelect.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method returns a copy of the set of the HasExternalReferences_Inverse attribute.
	*
	* @return a copy of the HasExternalReferences_Inverse set
	**/
	public SET<IfcExternalReferenceRelationship> getHasExternalReferences_Inverse()
	{
		if(this.HasExternalReferences_Inverse != null)
			return new SET<IfcExternalReferenceRelationship>(this.HasExternalReferences_Inverse);
		return null;
	}

	/**
	* This method returns a copy of the set of the ApprovedObjects_Inverse attribute.
	*
	* @return a copy of the ApprovedObjects_Inverse set
	**/
	public SET<IfcRelAssociatesApproval> getApprovedObjects_Inverse()
	{
		if(this.ApprovedObjects_Inverse != null)
			return new SET<IfcRelAssociatesApproval>(this.ApprovedObjects_Inverse);
		return null;
	}

	/**
	* This method returns a copy of the set of the ApprovedResources_Inverse attribute.
	*
	* @return a copy of the ApprovedResources_Inverse set
	**/
	public SET<IfcResourceApprovalRelationship> getApprovedResources_Inverse()
	{
		if(this.ApprovedResources_Inverse != null)
			return new SET<IfcResourceApprovalRelationship>(this.ApprovedResources_Inverse);
		return null;
	}

	/**
	* This method returns a copy of the set of the IsRelatedWith_Inverse attribute.
	*
	* @return a copy of the IsRelatedWith_Inverse set
	**/
	public SET<IfcApprovalRelationship> getIsRelatedWith_Inverse()
	{
		if(this.IsRelatedWith_Inverse != null)
			return new SET<IfcApprovalRelationship>(this.IsRelatedWith_Inverse);
		return null;
	}

	/**
	* This method returns a copy of the set of the Relates_Inverse attribute.
	*
	* @return a copy of the Relates_Inverse set
	**/
	public SET<IfcApprovalRelationship> getRelates_Inverse()
	{
		if(this.Relates_Inverse != null)
			return new SET<IfcApprovalRelationship>(this.Relates_Inverse);
		return null;
	}

	/**
	* This method sets the Identifier attribute to the given value.
	*
	* @param Identifier DEMANDED value to set - may not be null
	**/
	public void setIdentifier(IfcIdentifier Identifier)
	{
		this.Identifier = Identifier;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Identifier attribute.
	*
	* @return the value of Identifier
	/**/
	public IfcIdentifier getIdentifier()
	{
		return this.Identifier;
	}

	/**
	* This method sets the Name attribute to the given value.
	*
	* @param Name DEMANDED value to set - may not be null
	**/
	public void setName(IfcLabel Name)
	{
		this.Name = Name;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Name attribute.
	*
	* @return the value of Name
	/**/
	public IfcLabel getName()
	{
		return this.Name;
	}

	/**
	* This method sets the Description attribute to the given value.
	*
	* @param Description DEMANDED value to set - may not be null
	**/
	public void setDescription(IfcText Description)
	{
		this.Description = Description;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Description attribute.
	*
	* @return the value of Description
	/**/
	public IfcText getDescription()
	{
		return this.Description;
	}

	/**
	* This method sets the TimeOfApproval attribute to the given value.
	*
	* @param TimeOfApproval DEMANDED value to set - may not be null
	**/
	public void setTimeOfApproval(IfcDateTime TimeOfApproval)
	{
		this.TimeOfApproval = TimeOfApproval;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the TimeOfApproval attribute.
	*
	* @return the value of TimeOfApproval
	/**/
	public IfcDateTime getTimeOfApproval()
	{
		return this.TimeOfApproval;
	}

	/**
	* This method sets the Status attribute to the given value.
	*
	* @param Status DEMANDED value to set - may not be null
	**/
	public void setStatus(IfcLabel Status)
	{
		this.Status = Status;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Status attribute.
	*
	* @return the value of Status
	/**/
	public IfcLabel getStatus()
	{
		return this.Status;
	}

	/**
	* This method sets the Level attribute to the given value.
	*
	* @param Level DEMANDED value to set - may not be null
	**/
	public void setLevel(IfcLabel Level)
	{
		this.Level = Level;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Level attribute.
	*
	* @return the value of Level
	/**/
	public IfcLabel getLevel()
	{
		return this.Level;
	}

	/**
	* This method sets the Qualifier attribute to the given value.
	*
	* @param Qualifier DEMANDED value to set - may not be null
	**/
	public void setQualifier(IfcText Qualifier)
	{
		this.Qualifier = Qualifier;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the Qualifier attribute.
	*
	* @return the value of Qualifier
	/**/
	public IfcText getQualifier()
	{
		return this.Qualifier;
	}

	/**
	* This method sets the RequestingApproval attribute to the given value.
	*
	* @param RequestingApproval DEMANDED value to set - may not be null
	**/
	public void setRequestingApproval(IfcActorSelect RequestingApproval)
	{
		this.RequestingApproval = RequestingApproval;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the RequestingApproval attribute.
	*
	* @return the value of RequestingApproval
	/**/
	public IfcActorSelect getRequestingApproval()
	{
		return this.RequestingApproval;
	}

	/**
	* This method sets the GivingApproval attribute to the given value.
	*
	* @param GivingApproval DEMANDED value to set - may not be null
	**/
	public void setGivingApproval(IfcActorSelect GivingApproval)
	{
		this.GivingApproval = GivingApproval;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the GivingApproval attribute.
	*
	* @return the value of GivingApproval
	/**/
	public IfcActorSelect getGivingApproval()
	{
		return this.GivingApproval;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcApproval ifcApproval = new IfcApproval();
		if(this.Identifier != null)
			ifcApproval.setIdentifier((IfcIdentifier)this.Identifier.clone());
		if(this.Name != null)
			ifcApproval.setName((IfcLabel)this.Name.clone());
		if(this.Description != null)
			ifcApproval.setDescription((IfcText)this.Description.clone());
		if(this.TimeOfApproval != null)
			ifcApproval.setTimeOfApproval((IfcDateTime)this.TimeOfApproval.clone());
		if(this.Status != null)
			ifcApproval.setStatus((IfcLabel)this.Status.clone());
		if(this.Level != null)
			ifcApproval.setLevel((IfcLabel)this.Level.clone());
		if(this.Qualifier != null)
			ifcApproval.setQualifier((IfcText)this.Qualifier.clone());
		if(this.RequestingApproval != null)
			ifcApproval.setRequestingApproval((IfcActorSelect)this.RequestingApproval.clone());
		if(this.GivingApproval != null)
			ifcApproval.setGivingApproval((IfcActorSelect)this.GivingApproval.clone());
		return ifcApproval;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcApproval ifcApproval = new IfcApproval();
		if(this.Identifier != null)
			ifcApproval.setIdentifier(this.Identifier);
		if(this.Name != null)
			ifcApproval.setName(this.Name);
		if(this.Description != null)
			ifcApproval.setDescription(this.Description);
		if(this.TimeOfApproval != null)
			ifcApproval.setTimeOfApproval(this.TimeOfApproval);
		if(this.Status != null)
			ifcApproval.setStatus(this.Status);
		if(this.Level != null)
			ifcApproval.setLevel(this.Level);
		if(this.Qualifier != null)
			ifcApproval.setQualifier(this.Qualifier);
		if(this.RequestingApproval != null)
			ifcApproval.setRequestingApproval(this.RequestingApproval);
		if(this.GivingApproval != null)
			ifcApproval.setGivingApproval(this.GivingApproval);
		return ifcApproval;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
