/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc4javatoolbox.ifc4;
/**
 * This is a default implementation of the entity IfcEvent<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcEvent extends IfcProcess implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcGloballyUniqueId","IfcOwnerHistory","IfcLabel","IfcText","IfcLabel","IfcIdentifier","IfcText","IfcEventTypeEnum","IfcEventTriggerTypeEnum","IfcLabel","IfcEventTime"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** PredefinedType is an OPTIONAL attribute**/
	protected IfcEventTypeEnum PredefinedType;
	/** EventTriggerType is an OPTIONAL attribute**/
	protected IfcEventTriggerTypeEnum EventTriggerType;
	/** UserDefinedEventTriggerType is an OPTIONAL attribute**/
	protected IfcLabel UserDefinedEventTriggerType;
	/** EventOccurenceTime is an OPTIONAL attribute**/
	protected IfcEventTime EventOccurenceTime;
	/**
	* The default constructor.
	**/
	public IfcEvent(){}

	/**
	* Constructs a new IfcEvent object using the given parameters.
	*
	* @param GlobalId DEMANDED parameter of type IfcGloballyUniqueId - may not be null.
	* @param OwnerHistory OPTIONAL parameter of type IfcOwnerHistory
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param ObjectType OPTIONAL parameter of type IfcLabel
	* @param Identification OPTIONAL parameter of type IfcIdentifier
	* @param LongDescription OPTIONAL parameter of type IfcText
	* @param PredefinedType OPTIONAL parameter of type IfcEventTypeEnum
	* @param EventTriggerType OPTIONAL parameter of type IfcEventTriggerTypeEnum
	* @param UserDefinedEventTriggerType OPTIONAL parameter of type IfcLabel
	* @param EventOccurenceTime OPTIONAL parameter of type IfcEventTime
	**/
	public IfcEvent(IfcGloballyUniqueId GlobalId, IfcOwnerHistory OwnerHistory, IfcLabel Name, IfcText Description, IfcLabel ObjectType, IfcIdentifier Identification, IfcText LongDescription, IfcEventTypeEnum PredefinedType, IfcEventTriggerTypeEnum EventTriggerType, IfcLabel UserDefinedEventTriggerType, IfcEventTime EventOccurenceTime)
	{
		this.GlobalId = GlobalId;
		this.OwnerHistory = OwnerHistory;
		this.Name = Name;
		this.Description = Description;
		this.ObjectType = ObjectType;
		this.Identification = Identification;
		this.LongDescription = LongDescription;
		this.PredefinedType = PredefinedType;
		this.EventTriggerType = EventTriggerType;
		this.UserDefinedEventTriggerType = UserDefinedEventTriggerType;
		this.EventOccurenceTime = EventOccurenceTime;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcEvent object using the given parameters.
	*
	* @param GlobalId DEMANDED parameter of type IfcGloballyUniqueId - may not be null.
	* @param OwnerHistory OPTIONAL parameter of type IfcOwnerHistory
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param ObjectType OPTIONAL parameter of type IfcLabel
	* @param Identification OPTIONAL parameter of type IfcIdentifier
	* @param LongDescription OPTIONAL parameter of type IfcText
	* @param PredefinedType OPTIONAL parameter of type IfcEventTypeEnum
	* @param EventTriggerType OPTIONAL parameter of type IfcEventTriggerTypeEnum
	* @param UserDefinedEventTriggerType OPTIONAL parameter of type IfcLabel
	* @param EventOccurenceTime OPTIONAL parameter of type IfcEventTime
	**/
	public void setParameters(IfcGloballyUniqueId GlobalId, IfcOwnerHistory OwnerHistory, IfcLabel Name, IfcText Description, IfcLabel ObjectType, IfcIdentifier Identification, IfcText LongDescription, IfcEventTypeEnum PredefinedType, IfcEventTriggerTypeEnum EventTriggerType, IfcLabel UserDefinedEventTriggerType, IfcEventTime EventOccurenceTime)
	{
		this.GlobalId = GlobalId;
		this.OwnerHistory = OwnerHistory;
		this.Name = Name;
		this.Description = Description;
		this.ObjectType = ObjectType;
		this.Identification = Identification;
		this.LongDescription = LongDescription;
		this.PredefinedType = PredefinedType;
		this.EventTriggerType = EventTriggerType;
		this.UserDefinedEventTriggerType = UserDefinedEventTriggerType;
		this.EventOccurenceTime = EventOccurenceTime;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.GlobalId = (IfcGloballyUniqueId) parameters.get(0);
		this.OwnerHistory = (IfcOwnerHistory) parameters.get(1);
		this.Name = (IfcLabel) parameters.get(2);
		this.Description = (IfcText) parameters.get(3);
		this.ObjectType = (IfcLabel) parameters.get(4);
		this.Identification = (IfcIdentifier) parameters.get(5);
		this.LongDescription = (IfcText) parameters.get(6);
		this.PredefinedType = (IfcEventTypeEnum) parameters.get(7);
		this.EventTriggerType = (IfcEventTriggerTypeEnum) parameters.get(8);
		this.UserDefinedEventTriggerType = (IfcLabel) parameters.get(9);
		this.EventOccurenceTime = (IfcEventTime) parameters.get(10);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcEvent.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCEVENT(");
		if(getRedefinedDerivedAttributeTypes().contains("GlobalId")) stepString = stepString.concat("*,");
		else{
		if(this.GlobalId != null)		stepString = stepString.concat(((RootInterface)this.GlobalId).getStepParameter(IfcGloballyUniqueId.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("OwnerHistory")) stepString = stepString.concat("*,");
		else{
		if(this.OwnerHistory != null)		stepString = stepString.concat(((RootInterface)this.OwnerHistory).getStepParameter(IfcOwnerHistory.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Name")) stepString = stepString.concat("*,");
		else{
		if(this.Name != null)		stepString = stepString.concat(((RootInterface)this.Name).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Description")) stepString = stepString.concat("*,");
		else{
		if(this.Description != null)		stepString = stepString.concat(((RootInterface)this.Description).getStepParameter(IfcText.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ObjectType")) stepString = stepString.concat("*,");
		else{
		if(this.ObjectType != null)		stepString = stepString.concat(((RootInterface)this.ObjectType).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Identification")) stepString = stepString.concat("*,");
		else{
		if(this.Identification != null)		stepString = stepString.concat(((RootInterface)this.Identification).getStepParameter(IfcIdentifier.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("LongDescription")) stepString = stepString.concat("*,");
		else{
		if(this.LongDescription != null)		stepString = stepString.concat(((RootInterface)this.LongDescription).getStepParameter(IfcText.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("PredefinedType")) stepString = stepString.concat("*,");
		else{
		if(this.PredefinedType != null)		stepString = stepString.concat(((RootInterface)this.PredefinedType).getStepParameter(IfcEventTypeEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("EventTriggerType")) stepString = stepString.concat("*,");
		else{
		if(this.EventTriggerType != null)		stepString = stepString.concat(((RootInterface)this.EventTriggerType).getStepParameter(IfcEventTriggerTypeEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("UserDefinedEventTriggerType")) stepString = stepString.concat("*,");
		else{
		if(this.UserDefinedEventTriggerType != null)		stepString = stepString.concat(((RootInterface)this.UserDefinedEventTriggerType).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("EventOccurenceTime")) stepString = stepString.concat("*);");
		else{
		if(this.EventOccurenceTime != null)		stepString = stepString.concat(((RootInterface)this.EventOccurenceTime).getStepParameter(IfcEventTime.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the PredefinedType attribute to the given value.
	*
	* @param PredefinedType DEMANDED value to set - may not be null
	**/
	public void setPredefinedType(IfcEventTypeEnum PredefinedType)
	{
		this.PredefinedType = PredefinedType;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the PredefinedType attribute.
	*
	* @return the value of PredefinedType
	/**/
	public IfcEventTypeEnum getPredefinedType()
	{
		return this.PredefinedType;
	}

	/**
	* This method sets the EventTriggerType attribute to the given value.
	*
	* @param EventTriggerType DEMANDED value to set - may not be null
	**/
	public void setEventTriggerType(IfcEventTriggerTypeEnum EventTriggerType)
	{
		this.EventTriggerType = EventTriggerType;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the EventTriggerType attribute.
	*
	* @return the value of EventTriggerType
	/**/
	public IfcEventTriggerTypeEnum getEventTriggerType()
	{
		return this.EventTriggerType;
	}

	/**
	* This method sets the UserDefinedEventTriggerType attribute to the given value.
	*
	* @param UserDefinedEventTriggerType DEMANDED value to set - may not be null
	**/
	public void setUserDefinedEventTriggerType(IfcLabel UserDefinedEventTriggerType)
	{
		this.UserDefinedEventTriggerType = UserDefinedEventTriggerType;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the UserDefinedEventTriggerType attribute.
	*
	* @return the value of UserDefinedEventTriggerType
	/**/
	public IfcLabel getUserDefinedEventTriggerType()
	{
		return this.UserDefinedEventTriggerType;
	}

	/**
	* This method sets the EventOccurenceTime attribute to the given value.
	*
	* @param EventOccurenceTime DEMANDED value to set - may not be null
	**/
	public void setEventOccurenceTime(IfcEventTime EventOccurenceTime)
	{
		this.EventOccurenceTime = EventOccurenceTime;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the EventOccurenceTime attribute.
	*
	* @return the value of EventOccurenceTime
	/**/
	public IfcEventTime getEventOccurenceTime()
	{
		return this.EventOccurenceTime;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcEvent ifcEvent = new IfcEvent();
		if(this.GlobalId != null)
			ifcEvent.setGlobalId((IfcGloballyUniqueId)this.GlobalId.clone());
		if(this.OwnerHistory != null)
			ifcEvent.setOwnerHistory((IfcOwnerHistory)this.OwnerHistory.clone());
		if(this.Name != null)
			ifcEvent.setName((IfcLabel)this.Name.clone());
		if(this.Description != null)
			ifcEvent.setDescription((IfcText)this.Description.clone());
		if(this.ObjectType != null)
			ifcEvent.setObjectType((IfcLabel)this.ObjectType.clone());
		if(this.Identification != null)
			ifcEvent.setIdentification((IfcIdentifier)this.Identification.clone());
		if(this.LongDescription != null)
			ifcEvent.setLongDescription((IfcText)this.LongDescription.clone());
		if(this.PredefinedType != null)
			ifcEvent.setPredefinedType((IfcEventTypeEnum)this.PredefinedType.clone());
		if(this.EventTriggerType != null)
			ifcEvent.setEventTriggerType((IfcEventTriggerTypeEnum)this.EventTriggerType.clone());
		if(this.UserDefinedEventTriggerType != null)
			ifcEvent.setUserDefinedEventTriggerType((IfcLabel)this.UserDefinedEventTriggerType.clone());
		if(this.EventOccurenceTime != null)
			ifcEvent.setEventOccurenceTime((IfcEventTime)this.EventOccurenceTime.clone());
		return ifcEvent;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcEvent ifcEvent = new IfcEvent();
		if(this.GlobalId != null)
			ifcEvent.setGlobalId(this.GlobalId);
		if(this.OwnerHistory != null)
			ifcEvent.setOwnerHistory(this.OwnerHistory);
		if(this.Name != null)
			ifcEvent.setName(this.Name);
		if(this.Description != null)
			ifcEvent.setDescription(this.Description);
		if(this.ObjectType != null)
			ifcEvent.setObjectType(this.ObjectType);
		if(this.Identification != null)
			ifcEvent.setIdentification(this.Identification);
		if(this.LongDescription != null)
			ifcEvent.setLongDescription(this.LongDescription);
		if(this.PredefinedType != null)
			ifcEvent.setPredefinedType(this.PredefinedType);
		if(this.EventTriggerType != null)
			ifcEvent.setEventTriggerType(this.EventTriggerType);
		if(this.UserDefinedEventTriggerType != null)
			ifcEvent.setUserDefinedEventTriggerType(this.UserDefinedEventTriggerType);
		if(this.EventOccurenceTime != null)
			ifcEvent.setEventOccurenceTime(this.EventOccurenceTime);
		return ifcEvent;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
