/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc4javatoolbox.ifc4;
/**
 * This is a default implementation of the entity IfcEventTime<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcEventTime extends IfcSchedulingTime implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcLabel","IfcDataOriginEnum","IfcLabel","IfcDateTime","IfcDateTime","IfcDateTime","IfcDateTime"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** ActualDate is an OPTIONAL attribute**/
	protected IfcDateTime ActualDate;
	/** EarlyDate is an OPTIONAL attribute**/
	protected IfcDateTime EarlyDate;
	/** LateDate is an OPTIONAL attribute**/
	protected IfcDateTime LateDate;
	/** ScheduleDate is an OPTIONAL attribute**/
	protected IfcDateTime ScheduleDate;
	/**
	* The default constructor.
	**/
	public IfcEventTime(){}

	/**
	* Constructs a new IfcEventTime object using the given parameters.
	*
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param DataOrigin OPTIONAL parameter of type IfcDataOriginEnum
	* @param UserDefinedDataOrigin OPTIONAL parameter of type IfcLabel
	* @param ActualDate OPTIONAL parameter of type IfcDateTime
	* @param EarlyDate OPTIONAL parameter of type IfcDateTime
	* @param LateDate OPTIONAL parameter of type IfcDateTime
	* @param ScheduleDate OPTIONAL parameter of type IfcDateTime
	**/
	public IfcEventTime(IfcLabel Name, IfcDataOriginEnum DataOrigin, IfcLabel UserDefinedDataOrigin, IfcDateTime ActualDate, IfcDateTime EarlyDate, IfcDateTime LateDate, IfcDateTime ScheduleDate)
	{
		this.Name = Name;
		this.DataOrigin = DataOrigin;
		this.UserDefinedDataOrigin = UserDefinedDataOrigin;
		this.ActualDate = ActualDate;
		this.EarlyDate = EarlyDate;
		this.LateDate = LateDate;
		this.ScheduleDate = ScheduleDate;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcEventTime object using the given parameters.
	*
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param DataOrigin OPTIONAL parameter of type IfcDataOriginEnum
	* @param UserDefinedDataOrigin OPTIONAL parameter of type IfcLabel
	* @param ActualDate OPTIONAL parameter of type IfcDateTime
	* @param EarlyDate OPTIONAL parameter of type IfcDateTime
	* @param LateDate OPTIONAL parameter of type IfcDateTime
	* @param ScheduleDate OPTIONAL parameter of type IfcDateTime
	**/
	public void setParameters(IfcLabel Name, IfcDataOriginEnum DataOrigin, IfcLabel UserDefinedDataOrigin, IfcDateTime ActualDate, IfcDateTime EarlyDate, IfcDateTime LateDate, IfcDateTime ScheduleDate)
	{
		this.Name = Name;
		this.DataOrigin = DataOrigin;
		this.UserDefinedDataOrigin = UserDefinedDataOrigin;
		this.ActualDate = ActualDate;
		this.EarlyDate = EarlyDate;
		this.LateDate = LateDate;
		this.ScheduleDate = ScheduleDate;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.Name = (IfcLabel) parameters.get(0);
		this.DataOrigin = (IfcDataOriginEnum) parameters.get(1);
		this.UserDefinedDataOrigin = (IfcLabel) parameters.get(2);
		this.ActualDate = (IfcDateTime) parameters.get(3);
		this.EarlyDate = (IfcDateTime) parameters.get(4);
		this.LateDate = (IfcDateTime) parameters.get(5);
		this.ScheduleDate = (IfcDateTime) parameters.get(6);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcEventTime.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCEVENTTIME(");
		if(getRedefinedDerivedAttributeTypes().contains("Name")) stepString = stepString.concat("*,");
		else{
		if(this.Name != null)		stepString = stepString.concat(((RootInterface)this.Name).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("DataOrigin")) stepString = stepString.concat("*,");
		else{
		if(this.DataOrigin != null)		stepString = stepString.concat(((RootInterface)this.DataOrigin).getStepParameter(IfcDataOriginEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("UserDefinedDataOrigin")) stepString = stepString.concat("*,");
		else{
		if(this.UserDefinedDataOrigin != null)		stepString = stepString.concat(((RootInterface)this.UserDefinedDataOrigin).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ActualDate")) stepString = stepString.concat("*,");
		else{
		if(this.ActualDate != null)		stepString = stepString.concat(((RootInterface)this.ActualDate).getStepParameter(IfcDateTime.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("EarlyDate")) stepString = stepString.concat("*,");
		else{
		if(this.EarlyDate != null)		stepString = stepString.concat(((RootInterface)this.EarlyDate).getStepParameter(IfcDateTime.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("LateDate")) stepString = stepString.concat("*,");
		else{
		if(this.LateDate != null)		stepString = stepString.concat(((RootInterface)this.LateDate).getStepParameter(IfcDateTime.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ScheduleDate")) stepString = stepString.concat("*);");
		else{
		if(this.ScheduleDate != null)		stepString = stepString.concat(((RootInterface)this.ScheduleDate).getStepParameter(IfcDateTime.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the ActualDate attribute to the given value.
	*
	* @param ActualDate DEMANDED value to set - may not be null
	**/
	public void setActualDate(IfcDateTime ActualDate)
	{
		this.ActualDate = ActualDate;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the ActualDate attribute.
	*
	* @return the value of ActualDate
	/**/
	public IfcDateTime getActualDate()
	{
		return this.ActualDate;
	}

	/**
	* This method sets the EarlyDate attribute to the given value.
	*
	* @param EarlyDate DEMANDED value to set - may not be null
	**/
	public void setEarlyDate(IfcDateTime EarlyDate)
	{
		this.EarlyDate = EarlyDate;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the EarlyDate attribute.
	*
	* @return the value of EarlyDate
	/**/
	public IfcDateTime getEarlyDate()
	{
		return this.EarlyDate;
	}

	/**
	* This method sets the LateDate attribute to the given value.
	*
	* @param LateDate DEMANDED value to set - may not be null
	**/
	public void setLateDate(IfcDateTime LateDate)
	{
		this.LateDate = LateDate;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the LateDate attribute.
	*
	* @return the value of LateDate
	/**/
	public IfcDateTime getLateDate()
	{
		return this.LateDate;
	}

	/**
	* This method sets the ScheduleDate attribute to the given value.
	*
	* @param ScheduleDate DEMANDED value to set - may not be null
	**/
	public void setScheduleDate(IfcDateTime ScheduleDate)
	{
		this.ScheduleDate = ScheduleDate;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the ScheduleDate attribute.
	*
	* @return the value of ScheduleDate
	/**/
	public IfcDateTime getScheduleDate()
	{
		return this.ScheduleDate;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcEventTime ifcEventTime = new IfcEventTime();
		if(this.Name != null)
			ifcEventTime.setName((IfcLabel)this.Name.clone());
		if(this.DataOrigin != null)
			ifcEventTime.setDataOrigin((IfcDataOriginEnum)this.DataOrigin.clone());
		if(this.UserDefinedDataOrigin != null)
			ifcEventTime.setUserDefinedDataOrigin((IfcLabel)this.UserDefinedDataOrigin.clone());
		if(this.ActualDate != null)
			ifcEventTime.setActualDate((IfcDateTime)this.ActualDate.clone());
		if(this.EarlyDate != null)
			ifcEventTime.setEarlyDate((IfcDateTime)this.EarlyDate.clone());
		if(this.LateDate != null)
			ifcEventTime.setLateDate((IfcDateTime)this.LateDate.clone());
		if(this.ScheduleDate != null)
			ifcEventTime.setScheduleDate((IfcDateTime)this.ScheduleDate.clone());
		return ifcEventTime;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcEventTime ifcEventTime = new IfcEventTime();
		if(this.Name != null)
			ifcEventTime.setName(this.Name);
		if(this.DataOrigin != null)
			ifcEventTime.setDataOrigin(this.DataOrigin);
		if(this.UserDefinedDataOrigin != null)
			ifcEventTime.setUserDefinedDataOrigin(this.UserDefinedDataOrigin);
		if(this.ActualDate != null)
			ifcEventTime.setActualDate(this.ActualDate);
		if(this.EarlyDate != null)
			ifcEventTime.setEarlyDate(this.EarlyDate);
		if(this.LateDate != null)
			ifcEventTime.setLateDate(this.LateDate);
		if(this.ScheduleDate != null)
			ifcEventTime.setScheduleDate(this.ScheduleDate);
		return ifcEventTime;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
