/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc4javatoolbox.ifc4;
/**
 * This is a default implementation of the entity IfcReparametrisedCompositeCurveSegment<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcReparametrisedCompositeCurveSegment extends IfcCompositeCurveSegment implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcTransitionCode","BOOLEAN","IfcCurve","IfcParameterValue"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** ParamLength is an DEMANDED attribute - may not be null**/
	protected IfcParameterValue ParamLength;
	/**
	* The default constructor.
	**/
	public IfcReparametrisedCompositeCurveSegment(){}

	/**
	* Constructs a new IfcReparametrisedCompositeCurveSegment object using the given parameters.
	*
	* @param Transition DEMANDED parameter of type IfcTransitionCode - may not be null.
	* @param SameSense DEMANDED parameter of type BOOLEAN - may not be null.
	* @param ParentCurve DEMANDED parameter of type IfcCurve - may not be null.
	* @param ParamLength DEMANDED parameter of type IfcParameterValue - may not be null.
	**/
	public IfcReparametrisedCompositeCurveSegment(IfcTransitionCode Transition, BOOLEAN SameSense, IfcCurve ParentCurve, IfcParameterValue ParamLength)
	{
		this.Transition = Transition;
		this.SameSense = SameSense;
		this.ParentCurve = ParentCurve;
		this.ParamLength = ParamLength;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcReparametrisedCompositeCurveSegment object using the given parameters.
	*
	* @param Transition DEMANDED parameter of type IfcTransitionCode - may not be null.
	* @param SameSense DEMANDED parameter of type BOOLEAN - may not be null.
	* @param ParentCurve DEMANDED parameter of type IfcCurve - may not be null.
	* @param ParamLength DEMANDED parameter of type IfcParameterValue - may not be null.
	**/
	public void setParameters(IfcTransitionCode Transition, BOOLEAN SameSense, IfcCurve ParentCurve, IfcParameterValue ParamLength)
	{
		this.Transition = Transition;
		this.SameSense = SameSense;
		this.ParentCurve = ParentCurve;
		this.ParamLength = ParamLength;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.Transition = (IfcTransitionCode) parameters.get(0);
		this.SameSense = (BOOLEAN) parameters.get(1);
		this.ParentCurve = (IfcCurve) parameters.get(2);
		this.ParamLength = (IfcParameterValue) parameters.get(3);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcReparametrisedCompositeCurveSegment.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCREPARAMETRISEDCOMPOSITECURVESEGMENT(");
		if(getRedefinedDerivedAttributeTypes().contains("Transition")) stepString = stepString.concat("*,");
		else{
		if(this.Transition != null)		stepString = stepString.concat(((RootInterface)this.Transition).getStepParameter(IfcTransitionCode.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("SameSense")) stepString = stepString.concat("*,");
		else{
		if(this.SameSense != null)		stepString = stepString.concat(((RootInterface)this.SameSense).getStepParameter(BOOLEAN.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ParentCurve")) stepString = stepString.concat("*,");
		else{
		if(this.ParentCurve != null)		stepString = stepString.concat(((RootInterface)this.ParentCurve).getStepParameter(IfcCurve.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ParamLength")) stepString = stepString.concat("*);");
		else{
		if(this.ParamLength != null)		stepString = stepString.concat(((RootInterface)this.ParamLength).getStepParameter(IfcParameterValue.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the ParamLength attribute to the given value.
	*
	* @param ParamLength OPTIONAL value to set
	**/
	public void setParamLength(IfcParameterValue ParamLength)
	{
		this.ParamLength = ParamLength;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the ParamLength attribute.
	*
	* @return the value of ParamLength
	/**/
	public IfcParameterValue getParamLength()
	{
		return this.ParamLength;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcReparametrisedCompositeCurveSegment ifcReparametrisedCompositeCurveSegment = new IfcReparametrisedCompositeCurveSegment();
		if(this.Transition != null)
			ifcReparametrisedCompositeCurveSegment.setTransition((IfcTransitionCode)this.Transition.clone());
		if(this.SameSense != null)
			ifcReparametrisedCompositeCurveSegment.setSameSense((BOOLEAN)this.SameSense.clone());
		if(this.ParentCurve != null)
			ifcReparametrisedCompositeCurveSegment.setParentCurve((IfcCurve)this.ParentCurve.clone());
		if(this.ParamLength != null)
			ifcReparametrisedCompositeCurveSegment.setParamLength((IfcParameterValue)this.ParamLength.clone());
		return ifcReparametrisedCompositeCurveSegment;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcReparametrisedCompositeCurveSegment ifcReparametrisedCompositeCurveSegment = new IfcReparametrisedCompositeCurveSegment();
		if(this.Transition != null)
			ifcReparametrisedCompositeCurveSegment.setTransition(this.Transition);
		if(this.SameSense != null)
			ifcReparametrisedCompositeCurveSegment.setSameSense(this.SameSense);
		if(this.ParentCurve != null)
			ifcReparametrisedCompositeCurveSegment.setParentCurve(this.ParentCurve);
		if(this.ParamLength != null)
			ifcReparametrisedCompositeCurveSegment.setParamLength(this.ParamLength);
		return ifcReparametrisedCompositeCurveSegment;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
