/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc4javatoolbox.ifc4;
/**
 * This is a default implementation of the entity IfcRelDeclares<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcRelDeclares extends IfcRelationship implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcGloballyUniqueId","IfcOwnerHistory","IfcLabel","IfcText","IfcContext","SET<IfcDefinitionSelect>"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** RelatingContext is an DEMANDED attribute - may not be null**/
	protected IfcContext RelatingContext;
	/** RelatedDefinitions is an DEMANDED attribute - may not be null**/
	protected SET<IfcDefinitionSelect> RelatedDefinitions;
	/**
	* The default constructor.
	**/
	public IfcRelDeclares(){}

	/**
	* Constructs a new IfcRelDeclares object using the given parameters.
	*
	* @param GlobalId DEMANDED parameter of type IfcGloballyUniqueId - may not be null.
	* @param OwnerHistory OPTIONAL parameter of type IfcOwnerHistory
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param RelatingContext DEMANDED parameter of type IfcContext - may not be null.
	* @param RelatedDefinitions DEMANDED parameter of type SET<IfcDefinitionSelect> - may not be null.
	**/
	public IfcRelDeclares(IfcGloballyUniqueId GlobalId, IfcOwnerHistory OwnerHistory, IfcLabel Name, IfcText Description, IfcContext RelatingContext, SET<IfcDefinitionSelect> RelatedDefinitions)
	{
		this.GlobalId = GlobalId;
		this.OwnerHistory = OwnerHistory;
		this.Name = Name;
		this.Description = Description;
		this.RelatingContext = RelatingContext;
		this.RelatedDefinitions = RelatedDefinitions;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcRelDeclares object using the given parameters.
	*
	* @param GlobalId DEMANDED parameter of type IfcGloballyUniqueId - may not be null.
	* @param OwnerHistory OPTIONAL parameter of type IfcOwnerHistory
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param RelatingContext DEMANDED parameter of type IfcContext - may not be null.
	* @param RelatedDefinitions DEMANDED parameter of type SET<IfcDefinitionSelect> - may not be null.
	**/
	public void setParameters(IfcGloballyUniqueId GlobalId, IfcOwnerHistory OwnerHistory, IfcLabel Name, IfcText Description, IfcContext RelatingContext, SET<IfcDefinitionSelect> RelatedDefinitions)
	{
		this.GlobalId = GlobalId;
		this.OwnerHistory = OwnerHistory;
		this.Name = Name;
		this.Description = Description;
		this.RelatingContext = RelatingContext;
		this.RelatedDefinitions = RelatedDefinitions;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	@SuppressWarnings("unchecked")
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.GlobalId = (IfcGloballyUniqueId) parameters.get(0);
		this.OwnerHistory = (IfcOwnerHistory) parameters.get(1);
		this.Name = (IfcLabel) parameters.get(2);
		this.Description = (IfcText) parameters.get(3);
		this.RelatingContext = (IfcContext) parameters.get(4);
		this.RelatedDefinitions = (SET<IfcDefinitionSelect>) parameters.get(5);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
		if(RelatingContext != null)
		{
				if(RelatingContext.Declares_Inverse == null)
				{
					RelatingContext.Declares_Inverse = new SET<IfcRelDeclares>();
				}
				RelatingContext.Declares_Inverse.add(this);
		}
		if(RelatedDefinitions != null)
		{
			for(IfcDefinitionSelect RelatedDefinitions$ : RelatedDefinitions)
			{
				if(RelatedDefinitions$ instanceof IfcPropertyDefinition)
				{
				if(((IfcPropertyDefinition)RelatedDefinitions$).HasContext_Inverse == null)
				{
					((IfcPropertyDefinition)RelatedDefinitions$).HasContext_Inverse = new SET<IfcRelDeclares>();
				}
				((IfcPropertyDefinition)RelatedDefinitions$).HasContext_Inverse.add(this);
				}
				else if(RelatedDefinitions$ instanceof IfcObjectDefinition)
				{
				if(((IfcObjectDefinition)RelatedDefinitions$).HasContext_Inverse == null)
				{
					((IfcObjectDefinition)RelatedDefinitions$).HasContext_Inverse = new SET<IfcRelDeclares>();
				}
				((IfcObjectDefinition)RelatedDefinitions$).HasContext_Inverse.add(this);
				}
			}
		}
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcRelDeclares.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCRELDECLARES(");
		if(getRedefinedDerivedAttributeTypes().contains("GlobalId")) stepString = stepString.concat("*,");
		else{
		if(this.GlobalId != null)		stepString = stepString.concat(((RootInterface)this.GlobalId).getStepParameter(IfcGloballyUniqueId.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("OwnerHistory")) stepString = stepString.concat("*,");
		else{
		if(this.OwnerHistory != null)		stepString = stepString.concat(((RootInterface)this.OwnerHistory).getStepParameter(IfcOwnerHistory.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Name")) stepString = stepString.concat("*,");
		else{
		if(this.Name != null)		stepString = stepString.concat(((RootInterface)this.Name).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Description")) stepString = stepString.concat("*,");
		else{
		if(this.Description != null)		stepString = stepString.concat(((RootInterface)this.Description).getStepParameter(IfcText.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("RelatingContext")) stepString = stepString.concat("*,");
		else{
		if(this.RelatingContext != null)		stepString = stepString.concat(((RootInterface)this.RelatingContext).getStepParameter(IfcContext.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("RelatedDefinitions")) stepString = stepString.concat("*);");
		else{
		if(this.RelatedDefinitions != null)		stepString = stepString.concat(((RootInterface)this.RelatedDefinitions).getStepParameter(IfcDefinitionSelect.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the RelatingContext attribute to the given value.
	*
	* @param RelatingContext OPTIONAL value to set
	**/
	public void setRelatingContext(IfcContext RelatingContext)
	{
		synchronizeInversesRemoveRelatingContext(this.RelatingContext);
		this.RelatingContext = RelatingContext;
		synchronizeInversesAddRelatingContext(this.RelatingContext);
		fireChangeEvent();
	}

	/**
	* This method returns the value of the RelatingContext attribute.
	*
	* @return the value of RelatingContext
	/**/
	public IfcContext getRelatingContext()
	{
		return this.RelatingContext;
	}

	private void synchronizeInversesAddRelatingContext(IfcContext RelatingContext)
	{
		if(RelatingContext != null)
		{
				if(RelatingContext.Declares_Inverse == null)
				{
					RelatingContext.Declares_Inverse = new SET<IfcRelDeclares>();
				}
				RelatingContext.Declares_Inverse.add(this);
		}
	}

	private void synchronizeInversesRemoveRelatingContext(IfcContext RelatingContext)
	{
		if(RelatingContext != null)
		{
				if(RelatingContext.Declares_Inverse != null)
				{
					RelatingContext.Declares_Inverse.remove(this);
				}
		}
	}

	/**
	* This method sets the RelatedDefinitions attribute to the given value.
	*
	* @param RelatedDefinitions OPTIONAL value to set
	**/
	public void setRelatedDefinitions(SET<IfcDefinitionSelect> RelatedDefinitions)
	{
		synchronizeInversesRemoveRelatedDefinitions(this.RelatedDefinitions);
		this.RelatedDefinitions = RelatedDefinitions;
		synchronizeInversesAddRelatedDefinitions(this.RelatedDefinitions);
		fireChangeEvent();
	}

	/**
	* This method returns a copy of the set of the RelatedDefinitions attribute.
	*
	* @return a copy of the RelatedDefinitions set
	**/
	public SET<IfcDefinitionSelect> getRelatedDefinitions()
	{
		if(this.RelatedDefinitions != null)
			return new SET<IfcDefinitionSelect>(this.RelatedDefinitions);
		return null;
	}

	/**
	* This method adds an IfcDefinitionSelect object to the RelatedDefinitions set.
	* @param RelatedDefinitions element to be appended to this set.
	**/
	public void addRelatedDefinitions(IfcDefinitionSelect RelatedDefinitions)
	{
		if(this.RelatedDefinitions == null)
			this.RelatedDefinitions = new SET<IfcDefinitionSelect>();
		this.RelatedDefinitions.add(RelatedDefinitions);
		synchronizeInversesAddRelatedDefinitions(RelatedDefinitions);
		fireChangeEvent();
	}

	/**
	* This method adds a collection of IfcDefinitionSelect objects to the RelatedDefinitions set.
	* @param RelatedDefinitions collection containing elements to be added to this set.
	**/
	public void addAllRelatedDefinitions(java.util.Collection<IfcDefinitionSelect> RelatedDefinitions)
	{
		if(this.RelatedDefinitions == null)
			this.RelatedDefinitions = new SET<IfcDefinitionSelect>();
		this.RelatedDefinitions.addAll(RelatedDefinitions);
		synchronizeInversesAddRelatedDefinitions(RelatedDefinitions);
		fireChangeEvent();
	}

	/**
	* This method removes all elements from the RelatedDefinitions set.
	**/
	public void clearRelatedDefinitions()
	{
		if(this.RelatedDefinitions != null)
		{
			synchronizeInversesRemoveRelatedDefinitions(this.RelatedDefinitions);
			this.RelatedDefinitions.clear();
			fireChangeEvent();
		}
	}

	/**
	* This method removes an IfcDefinitionSelect object from the RelatedDefinitions set.
	* @param RelatedDefinitions element to be removed from this set.
	**/
	public void removeRelatedDefinitions(IfcDefinitionSelect RelatedDefinitions)
	{
		if(this.RelatedDefinitions != null)
		{
			this.RelatedDefinitions.remove(RelatedDefinitions);
			synchronizeInversesRemoveRelatedDefinitions(RelatedDefinitions);
			fireChangeEvent();
		}
	}

	/**
	* This method removes a collection of IfcDefinitionSelect objects from the RelatedDefinitions set.
	* @param RelatedDefinitions collection containing elements to be removed from this set.
	**/
	public void removeAllRelatedDefinitions(java.util.Collection<IfcDefinitionSelect> RelatedDefinitions)
	{
		if(this.RelatedDefinitions != null)
		{
			this.RelatedDefinitions.removeAll(RelatedDefinitions);
			synchronizeInversesRemoveRelatedDefinitions(RelatedDefinitions);
			fireChangeEvent();
		}
	}

	private void synchronizeInversesAddRelatedDefinitions(IfcDefinitionSelect RelatedDefinitions)
	{
		if(RelatedDefinitions != null)
		{
				if(RelatedDefinitions instanceof IfcPropertyDefinition)
				{
				if(((IfcPropertyDefinition)RelatedDefinitions).HasContext_Inverse == null)
				{
					((IfcPropertyDefinition)RelatedDefinitions).HasContext_Inverse = new SET<IfcRelDeclares>();
				}
				((IfcPropertyDefinition)RelatedDefinitions).HasContext_Inverse.add(this);
				}
				else if(RelatedDefinitions instanceof IfcObjectDefinition)
				{
				if(((IfcObjectDefinition)RelatedDefinitions).HasContext_Inverse == null)
				{
					((IfcObjectDefinition)RelatedDefinitions).HasContext_Inverse = new SET<IfcRelDeclares>();
				}
				((IfcObjectDefinition)RelatedDefinitions).HasContext_Inverse.add(this);
				}
		}
	}

	private void synchronizeInversesAddRelatedDefinitions(java.util.Collection<IfcDefinitionSelect> RelatedDefinitions)
	{
		if(RelatedDefinitions != null)
		{
			for(IfcDefinitionSelect RelatedDefinitions$ : RelatedDefinitions)
			{
				synchronizeInversesAddRelatedDefinitions(RelatedDefinitions$);
			}
		}
	}

	private void synchronizeInversesRemoveRelatedDefinitions(IfcDefinitionSelect RelatedDefinitions)
	{
		if(RelatedDefinitions != null)
		{
				if(RelatedDefinitions instanceof IfcPropertyDefinition)
				{
				if(((IfcPropertyDefinition)RelatedDefinitions).HasContext_Inverse != null)
				{
				((IfcPropertyDefinition)RelatedDefinitions).HasContext_Inverse.remove(this);
				}
				}
				else if(RelatedDefinitions instanceof IfcObjectDefinition)
				{
				if(((IfcObjectDefinition)RelatedDefinitions).HasContext_Inverse != null)
				{
				((IfcObjectDefinition)RelatedDefinitions).HasContext_Inverse.remove(this);
				}
				}
		}
	}

	private void synchronizeInversesRemoveRelatedDefinitions(java.util.Collection<IfcDefinitionSelect> RelatedDefinitions)
	{
		if(RelatedDefinitions != null)
		{
			for(IfcDefinitionSelect RelatedDefinitions$ : RelatedDefinitions)
			{
				synchronizeInversesRemoveRelatedDefinitions(RelatedDefinitions$);
			}
		}
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	@SuppressWarnings("unchecked")
	public Object clone()
	{
		IfcRelDeclares ifcRelDeclares = new IfcRelDeclares();
		if(this.GlobalId != null)
			ifcRelDeclares.setGlobalId((IfcGloballyUniqueId)this.GlobalId.clone());
		if(this.OwnerHistory != null)
			ifcRelDeclares.setOwnerHistory((IfcOwnerHistory)this.OwnerHistory.clone());
		if(this.Name != null)
			ifcRelDeclares.setName((IfcLabel)this.Name.clone());
		if(this.Description != null)
			ifcRelDeclares.setDescription((IfcText)this.Description.clone());
		if(this.RelatingContext != null)
			ifcRelDeclares.setRelatingContext((IfcContext)this.RelatingContext.clone());
		if(this.RelatedDefinitions != null)
			ifcRelDeclares.setRelatedDefinitions((SET<IfcDefinitionSelect>)this.RelatedDefinitions.clone());
		return ifcRelDeclares;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcRelDeclares ifcRelDeclares = new IfcRelDeclares();
		if(this.GlobalId != null)
			ifcRelDeclares.setGlobalId(this.GlobalId);
		if(this.OwnerHistory != null)
			ifcRelDeclares.setOwnerHistory(this.OwnerHistory);
		if(this.Name != null)
			ifcRelDeclares.setName(this.Name);
		if(this.Description != null)
			ifcRelDeclares.setDescription(this.Description);
		if(this.RelatingContext != null)
			ifcRelDeclares.setRelatingContext(this.RelatingContext);
		if(this.RelatedDefinitions != null)
			ifcRelDeclares.setRelatedDefinitions(this.RelatedDefinitions);
		return ifcRelDeclares;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
