/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc4javatoolbox.ifc4;
/**
 * This is a default implementation of the entity IfcTextureMap<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcTextureMap extends IfcTextureCoordinate implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"LIST<IfcSurfaceTexture>","LIST<IfcTextureVertex>","IfcFace"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** Vertices is an DEMANDED attribute - may not be null**/
	protected LIST<IfcTextureVertex> Vertices;
	/** MappedTo is an DEMANDED attribute - may not be null**/
	protected IfcFace MappedTo;
	/**
	* The default constructor.
	**/
	public IfcTextureMap(){}

	/**
	* Constructs a new IfcTextureMap object using the given parameters.
	*
	* @param Maps DEMANDED parameter of type LIST<IfcSurfaceTexture> - may not be null.
	* @param Vertices DEMANDED parameter of type LIST<IfcTextureVertex> - may not be null.
	* @param MappedTo DEMANDED parameter of type IfcFace - may not be null.
	**/
	public IfcTextureMap(LIST<IfcSurfaceTexture> Maps, LIST<IfcTextureVertex> Vertices, IfcFace MappedTo)
	{
		this.Maps = Maps;
		this.Vertices = Vertices;
		this.MappedTo = MappedTo;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcTextureMap object using the given parameters.
	*
	* @param Maps DEMANDED parameter of type LIST<IfcSurfaceTexture> - may not be null.
	* @param Vertices DEMANDED parameter of type LIST<IfcTextureVertex> - may not be null.
	* @param MappedTo DEMANDED parameter of type IfcFace - may not be null.
	**/
	public void setParameters(LIST<IfcSurfaceTexture> Maps, LIST<IfcTextureVertex> Vertices, IfcFace MappedTo)
	{
		this.Maps = Maps;
		this.Vertices = Vertices;
		this.MappedTo = MappedTo;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	@SuppressWarnings("unchecked")
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.Maps = (LIST<IfcSurfaceTexture>) parameters.get(0);
		this.Vertices = (LIST<IfcTextureVertex>) parameters.get(1);
		this.MappedTo = (IfcFace) parameters.get(2);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
		if(Maps != null)
		{
			for(IfcSurfaceTexture Maps$ : Maps)
			{
				if(Maps$.IsMappedBy_Inverse == null)
				{
					Maps$.IsMappedBy_Inverse = new SET<IfcTextureCoordinate>();
				}
				Maps$.IsMappedBy_Inverse.add(this);
			}
		}
		if(MappedTo != null)
		{
				if(MappedTo.HasTextureMaps_Inverse == null)
				{
					MappedTo.HasTextureMaps_Inverse = new SET<IfcTextureMap>();
				}
				MappedTo.HasTextureMaps_Inverse.add(this);
		}
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcTextureMap.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCTEXTUREMAP(");
		if(getRedefinedDerivedAttributeTypes().contains("Maps")) stepString = stepString.concat("*,");
		else{
		if(this.Maps != null)		stepString = stepString.concat(((RootInterface)this.Maps).getStepParameter(IfcSurfaceTexture.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Vertices")) stepString = stepString.concat("*,");
		else{
		if(this.Vertices != null)		stepString = stepString.concat(((RootInterface)this.Vertices).getStepParameter(IfcTextureVertex.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("MappedTo")) stepString = stepString.concat("*);");
		else{
		if(this.MappedTo != null)		stepString = stepString.concat(((RootInterface)this.MappedTo).getStepParameter(IfcFace.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the Vertices attribute to the given value.
	*
	* @param Vertices OPTIONAL value to set
	**/
	public void setVertices(LIST<IfcTextureVertex> Vertices)
	{
		this.Vertices = Vertices;
		fireChangeEvent();
	}

	/**
	* This method returns a copy of the list of the Vertices attribute.
	*
	* @return a copy of the Vertices list
	**/
	public LIST<IfcTextureVertex> getVertices()
	{
		if(this.Vertices != null)
			return new LIST<IfcTextureVertex>(this.Vertices);
		return null;
	}

	/**
	* This method adds an IfcTextureVertex object to the Vertices list.
	* @param Vertices element to be appended to this list.
	**/
	public void addVertices(IfcTextureVertex Vertices)
	{
		if(this.Vertices == null)
			this.Vertices = new LIST<IfcTextureVertex>();
		this.Vertices.add(Vertices);
		fireChangeEvent();
	}

	/**
	* This method adds a collection of IfcTextureVertex objects to the Vertices list.
	* @param Vertices collection containing elements to be added to this list.
	**/
	public void addAllVertices(java.util.Collection<IfcTextureVertex> Vertices)
	{
		if(this.Vertices == null)
			this.Vertices = new LIST<IfcTextureVertex>();
		this.Vertices.addAll(Vertices);
		fireChangeEvent();
	}

	/**
	* This method removes all elements from the Vertices list.
	**/
	public void clearVertices()
	{
		if(this.Vertices != null)
		{
			this.Vertices.clear();
			fireChangeEvent();
		}
	}

	/**
	* This method removes an IfcTextureVertex object from the Vertices list.
	* @param Vertices element to be removed from this list.
	**/
	public void removeVertices(IfcTextureVertex Vertices)
	{
		if(this.Vertices != null)
		{
			this.Vertices.remove(Vertices);
			fireChangeEvent();
		}
	}

	/**
	* This method removes a collection of IfcTextureVertex objects from the Vertices list.
	* @param Vertices collection containing elements to be removed from this list.
	**/
	public void removeAllVertices(java.util.Collection<IfcTextureVertex> Vertices)
	{
		if(this.Vertices != null)
		{
			this.Vertices.removeAll(Vertices);
			fireChangeEvent();
		}
	}

	/**
	* This method sets the MappedTo attribute to the given value.
	*
	* @param MappedTo OPTIONAL value to set
	**/
	public void setMappedTo(IfcFace MappedTo)
	{
		synchronizeInversesRemoveMappedTo(this.MappedTo);
		this.MappedTo = MappedTo;
		synchronizeInversesAddMappedTo(this.MappedTo);
		fireChangeEvent();
	}

	/**
	* This method returns the value of the MappedTo attribute.
	*
	* @return the value of MappedTo
	/**/
	public IfcFace getMappedTo()
	{
		return this.MappedTo;
	}

	private void synchronizeInversesAddMappedTo(IfcFace MappedTo)
	{
		if(MappedTo != null)
		{
				if(MappedTo.HasTextureMaps_Inverse == null)
				{
					MappedTo.HasTextureMaps_Inverse = new SET<IfcTextureMap>();
				}
				MappedTo.HasTextureMaps_Inverse.add(this);
		}
	}

	private void synchronizeInversesRemoveMappedTo(IfcFace MappedTo)
	{
		if(MappedTo != null)
		{
				if(MappedTo.HasTextureMaps_Inverse != null)
				{
					MappedTo.HasTextureMaps_Inverse.remove(this);
				}
		}
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	@SuppressWarnings("unchecked")
	public Object clone()
	{
		IfcTextureMap ifcTextureMap = new IfcTextureMap();
		if(this.Maps != null)
			ifcTextureMap.setMaps((LIST<IfcSurfaceTexture>)this.Maps.clone());
		if(this.Vertices != null)
			ifcTextureMap.setVertices((LIST<IfcTextureVertex>)this.Vertices.clone());
		if(this.MappedTo != null)
			ifcTextureMap.setMappedTo((IfcFace)this.MappedTo.clone());
		return ifcTextureMap;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcTextureMap ifcTextureMap = new IfcTextureMap();
		if(this.Maps != null)
			ifcTextureMap.setMaps(this.Maps);
		if(this.Vertices != null)
			ifcTextureMap.setVertices(this.Vertices);
		if(this.MappedTo != null)
			ifcTextureMap.setMappedTo(this.MappedTo);
		return ifcTextureMap;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
